//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PI.Locales.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string LangSelector_Languages_Default {
            get {
                return ResourceManager.GetString("LangSelector_Languages_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LangSelector_Languages_English {
            get {
                return ResourceManager.GetString("LangSelector_Languages_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string LangSelector_Languages_Polish {
            get {
                return ResourceManager.GetString("LangSelector_Languages_Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string LangSelector_Ui_Down_OkBtn {
            get {
                return ResourceManager.GetString("LangSelector_Ui_Down_OkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language selector.
        /// </summary>
        internal static string LangSelector_Ui_Form_Text {
            get {
                return ResourceManager.GetString("LangSelector_Ui_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string MainWindow_Menu_Chart {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainWindow_Menu_Chart_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Chart_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Means.
        /// </summary>
        internal static string MainWindow_Menu_Means {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaging info.
        /// </summary>
        internal static string MainWindow_Menu_Means_AveragingInfo {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means_AveragingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainWindow_Menu_Means_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        internal static string MainWindow_Menu_Panel {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string MainWindow_Menu_Panel_Hide {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep proportions.
        /// </summary>
        internal static string MainWindow_Menu_Panel_KeepProportions {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_KeepProportions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string MainWindow_Menu_Panel_Lock {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string MainWindow_Menu_Program {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check update.
        /// </summary>
        internal static string MainWindow_Menu_Program_CheckUpdate {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MainWindow_Menu_Program_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string MainWindow_Menu_Program_SelectLanguage {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical analysis.
        /// </summary>
        internal static string MainWindow_Menu_Program_StatisticalAnalysis {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_StatisticalAnalysis", resourceCulture);
            }
        }
    }
}
