//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PI.Locales.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average.
        /// </summary>
        internal static string Enums_DataSetCurvesTypes_Average {
            get {
                return ResourceManager.GetString("Enums_DataSetCurvesTypes_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generated.
        /// </summary>
        internal static string Enums_DataSetCurvesTypes_Generated {
            get {
                return ResourceManager.GetString("Enums_DataSetCurvesTypes_Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pattern.
        /// </summary>
        internal static string Enums_DataSetCurvesTypes_Pattern {
            get {
                return ResourceManager.GetString("Enums_DataSetCurvesTypes_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGM.
        /// </summary>
        internal static string Enums_MeanTypes_AGM {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_AGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arithmetic.
        /// </summary>
        internal static string Enums_MeanTypes_Arithmetic {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Arithmetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom-differential.
        /// </summary>
        internal static string Enums_MeanTypes_CustomDifferential {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_CustomDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom-geometric.
        /// </summary>
        internal static string Enums_MeanTypes_CustomGeometric {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_CustomGeometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom-tolerance.
        /// </summary>
        internal static string Enums_MeanTypes_CustomTolerance {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_CustomTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMA.
        /// </summary>
        internal static string Enums_MeanTypes_EMA {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_EMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geometric.
        /// </summary>
        internal static string Enums_MeanTypes_Geometric {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Geometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to harmonic.
        /// </summary>
        internal static string Enums_MeanTypes_Harmonic {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Harmonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heronian.
        /// </summary>
        internal static string Enums_MeanTypes_Heronian {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Heronian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log waged.
        /// </summary>
        internal static string Enums_MeanTypes_LnWages {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_LnWages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logarithmic.
        /// </summary>
        internal static string Enums_MeanTypes_Logarithmic {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Logarithmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum.
        /// </summary>
        internal static string Enums_MeanTypes_Maximum {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mediana.
        /// </summary>
        internal static string Enums_MeanTypes_Mediana {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Mediana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum.
        /// </summary>
        internal static string Enums_MeanTypes_Minimum {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to power.
        /// </summary>
        internal static string Enums_MeanTypes_Power {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS.
        /// </summary>
        internal static string Enums_MeanTypes_RMS {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_RMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string LangSelector_Languages_Default {
            get {
                return ResourceManager.GetString("LangSelector_Languages_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LangSelector_Languages_English {
            get {
                return ResourceManager.GetString("LangSelector_Languages_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string LangSelector_Languages_Polish {
            get {
                return ResourceManager.GetString("LangSelector_Languages_Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string LangSelector_Ui_Down_OkBtn {
            get {
                return ResourceManager.GetString("LangSelector_Ui_Down_OkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language selector.
        /// </summary>
        internal static string LangSelector_Ui_Form_Text {
            get {
                return ResourceManager.GetString("LangSelector_Ui_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string MainWindow_Menu_Chart {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainWindow_Menu_Chart_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Chart_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Means.
        /// </summary>
        internal static string MainWindow_Menu_Means {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaging info.
        /// </summary>
        internal static string MainWindow_Menu_Means_AveragingInfo {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means_AveragingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainWindow_Menu_Means_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        internal static string MainWindow_Menu_Panel {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string MainWindow_Menu_Panel_Hide {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep proportions.
        /// </summary>
        internal static string MainWindow_Menu_Panel_KeepProportions {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_KeepProportions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string MainWindow_Menu_Panel_Lock {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string MainWindow_Menu_Program {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check update.
        /// </summary>
        internal static string MainWindow_Menu_Program_CheckUpdate {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MainWindow_Menu_Program_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string MainWindow_Menu_Program_SelectLanguage {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical analysis.
        /// </summary>
        internal static string MainWindow_Menu_Program_StatisticalAnalysis {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_StatisticalAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasheet.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve index:.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_CurveIndex {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_CurveIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of curves:.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_CurvesNumber {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_CurvesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve type:.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_CurveType {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_CurveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset control.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_DatasetControl {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_DatasetControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian noise.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_GaussianNoise {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_GaussianNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malform.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_Malform {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_Malform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dataset.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_ShowDataSet {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_ShowDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrounding:.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_Surrounding {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_Surrounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string MainWindow_Panel_Generate {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string MainWindow_Panel_Generate_Apply {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaging.
        /// </summary>
        internal static string MainWindow_Panel_Generate_Averaging {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_Averaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve scaffold:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_CurveScaffold1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_CurveScaffold1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic.
        /// </summary>
        internal static string MainWindow_Panel_Generate_CurveScaffold2_Hyperbolic {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_CurveScaffold2_Hyperbolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not chosen.
        /// </summary>
        internal static string MainWindow_Panel_Generate_CurveScaffold2_NotChosen {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_CurveScaffold2_NotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polynomial.
        /// </summary>
        internal static string MainWindow_Panel_Generate_CurveScaffold2_Polynomial {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_CurveScaffold2_Polynomial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waveform.
        /// </summary>
        internal static string MainWindow_Panel_Generate_CurveScaffold2_Waveform {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_CurveScaffold2_Waveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole set of curves.
        /// </summary>
        internal static string MainWindow_Panel_Generate_CurvesSet {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_CurvesSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define.
        /// </summary>
        internal static string MainWindow_Panel_Generate_Define {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_Define", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval points:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_Density {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending X point:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_EndingXPoint {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_EndingXPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate set.
        /// </summary>
        internal static string MainWindow_Panel_Generate_GenerateSet {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_GenerateSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean type:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_MeanType {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_MeanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of curves:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_NumberOfCurves1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_NumberOfCurves1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of curves:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_NumberOfCurves2 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_NumberOfCurves2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern curve scaffold.
        /// </summary>
        internal static string MainWindow_Panel_Generate_PatternCurveScaffold {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_PatternCurveScaffold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting X point:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_StartingXPoint {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_StartingXPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string MainWindow_Panel_Program {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual state:.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts:.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_Counts1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_Counts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework:.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_DotNetFramework {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_DotNetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_Failure {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_InfoObtainingErrorText {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_InfoObtainingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_Informations {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_Logging {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log path:.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_LogPath1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_LogPath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS version:.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_OsVersion1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_OsVersion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_Success {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string MainWindow_Panel_Program_Timer {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer&apos;s thesis 1.3.
        /// </summary>
        internal static string MainWindow_Ui_Form_Text {
            get {
                return ResourceManager.GetString("MainWindow_Ui_Form_Text", resourceCulture);
            }
        }
    }
}
