//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PI.Locales.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_Form_Text {
            get {
                return ResourceManager.GetString("About_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company:.
        /// </summary>
        internal static string About_Ui_AssemblyMetadata_Company {
            get {
                return ResourceManager.GetString("About_Ui_AssemblyMetadata_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly metadata.
        /// </summary>
        internal static string About_Ui_AssemblyMetadata_Title {
            get {
                return ResourceManager.GetString("About_Ui_AssemblyMetadata_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string About_Ui_AssemblyMetadata_Version {
            get {
                return ResourceManager.GetString("About_Ui_AssemblyMetadata_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter:.
        /// </summary>
        internal static string About_Ui_Other_Counter {
            get {
                return ResourceManager.GetString("About_Ui_Other_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoter:.
        /// </summary>
        internal static string About_Ui_Other_Promoter1 {
            get {
                return ResourceManager.GetString("About_Ui_Other_Promoter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paweł Kowalczyk, PhD (DSc).
        /// </summary>
        internal static string About_Ui_Other_Promoter2 {
            get {
                return ResourceManager.GetString("About_Ui_Other_Promoter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository:.
        /// </summary>
        internal static string About_Ui_Other_Repository {
            get {
                return ResourceManager.GetString("About_Ui_Other_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string About_Ui_Other_Title {
            get {
                return ResourceManager.GetString("About_Ui_Other_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log path:.
        /// </summary>
        internal static string About_Ui_TechnicalInformations_LogPath {
            get {
                return ResourceManager.GetString("About_Ui_TechnicalInformations_LogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework:.
        /// </summary>
        internal static string About_Ui_TechnicalInformations_NETFramework {
            get {
                return ResourceManager.GetString("About_Ui_TechnicalInformations_NETFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical informations.
        /// </summary>
        internal static string About_Ui_TechnicalInformations_Title {
            get {
                return ResourceManager.GetString("About_Ui_TechnicalInformations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart settings.
        /// </summary>
        internal static string ChartSettings_Form_Text {
            get {
                return ResourceManager.GetString("ChartSettings_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to curve:.
        /// </summary>
        internal static string ChartSettings_Ui_General_ApplyToCurve {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_General_ApplyToCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ChartSettings_Ui_General_OK {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_General_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_Chart_Title {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_Chart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axes.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_ChartArea_Axes {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_ChartArea_Axes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart area.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_ChartArea_ChartArea {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_ChartArea_ChartArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart area.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_ChartArea_Title {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_ChartArea_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_Series_Title {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_Series_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllCells.
        /// </summary>
        internal static string Enums_AutoSizeColumnsMode_AllCells {
            get {
                return ResourceManager.GetString("Enums_AutoSizeColumnsMode_AllCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllCellsExceptHeader.
        /// </summary>
        internal static string Enums_AutoSizeColumnsMode_AllCellsExceptHeader {
            get {
                return ResourceManager.GetString("Enums_AutoSizeColumnsMode_AllCellsExceptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnHeader.
        /// </summary>
        internal static string Enums_AutoSizeColumnsMode_ColumnHeader {
            get {
                return ResourceManager.GetString("Enums_AutoSizeColumnsMode_ColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayedCells.
        /// </summary>
        internal static string Enums_AutoSizeColumnsMode_DisplayedCells {
            get {
                return ResourceManager.GetString("Enums_AutoSizeColumnsMode_DisplayedCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayedCellsExceptHeader.
        /// </summary>
        internal static string Enums_AutoSizeColumnsMode_DisplayedCellsExceptHeader {
            get {
                return ResourceManager.GetString("Enums_AutoSizeColumnsMode_DisplayedCellsExceptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        internal static string Enums_AutoSizeColumnsMode_Fill {
            get {
                return ResourceManager.GetString("Enums_AutoSizeColumnsMode_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Enums_AutoSizeColumnsMode_None {
            get {
                return ResourceManager.GetString("Enums_AutoSizeColumnsMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string Enums_Boolean_False {
            get {
                return ResourceManager.GetString("Enums_Boolean_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Enums_Boolean_True {
            get {
                return ResourceManager.GetString("Enums_Boolean_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string Enums_CurveApply_All {
            get {
                return ResourceManager.GetString("Enums_CurveApply_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average.
        /// </summary>
        internal static string Enums_CurveApply_Average {
            get {
                return ResourceManager.GetString("Enums_CurveApply_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ideal.
        /// </summary>
        internal static string Enums_CurveApply_Ideal {
            get {
                return ResourceManager.GetString("Enums_CurveApply_Ideal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modified.
        /// </summary>
        internal static string Enums_CurveApply_Modified {
            get {
                return ResourceManager.GetString("Enums_CurveApply_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average.
        /// </summary>
        internal static string Enums_DataSetCurveType_Average {
            get {
                return ResourceManager.GetString("Enums_DataSetCurveType_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ideal.
        /// </summary>
        internal static string Enums_DataSetCurveType_Ideal {
            get {
                return ResourceManager.GetString("Enums_DataSetCurveType_Ideal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modified.
        /// </summary>
        internal static string Enums_DataSetCurveType_Modified {
            get {
                return ResourceManager.GetString("Enums_DataSetCurveType_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absolute.
        /// </summary>
        internal static string Enums_GeometricMeanVariant_Absolute {
            get {
                return ResourceManager.GetString("Enums_GeometricMeanVariant_Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        internal static string Enums_GeometricMeanVariant_Offset {
            get {
                return ResourceManager.GetString("Enums_GeometricMeanVariant_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parity.
        /// </summary>
        internal static string Enums_GeometricMeanVariant_Parity {
            get {
                return ResourceManager.GetString("Enums_GeometricMeanVariant_Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign.
        /// </summary>
        internal static string Enums_GeometricMeanVariant_Sign {
            get {
                return ResourceManager.GetString("Enums_GeometricMeanVariant_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boxcar.
        /// </summary>
        internal static string Enums_KernelType_Boxcar {
            get {
                return ResourceManager.GetString("Enums_KernelType_Boxcar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epanechnikov.
        /// </summary>
        internal static string Enums_KernelType_Epanechnikov {
            get {
                return ResourceManager.GetString("Enums_KernelType_Epanechnikov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian.
        /// </summary>
        internal static string Enums_KernelType_Gaussian {
            get {
                return ResourceManager.GetString("Enums_KernelType_Gaussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Enums_Languages_English {
            get {
                return ResourceManager.GetString("Enums_Languages_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string Enums_Languages_Polish {
            get {
                return ResourceManager.GetString("Enums_Languages_Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGM.
        /// </summary>
        internal static string Enums_MeanType_AGM {
            get {
                return ResourceManager.GetString("Enums_MeanType_AGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arithmetic.
        /// </summary>
        internal static string Enums_MeanType_Arithmetic {
            get {
                return ResourceManager.GetString("Enums_MeanType_Arithmetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to central.
        /// </summary>
        internal static string Enums_MeanType_Central {
            get {
                return ResourceManager.GetString("Enums_MeanType_Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generalized.
        /// </summary>
        internal static string Enums_MeanType_Generalized {
            get {
                return ResourceManager.GetString("Enums_MeanType_Generalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geometric.
        /// </summary>
        internal static string Enums_MeanType_Geometric {
            get {
                return ResourceManager.GetString("Enums_MeanType_Geometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to harmonic.
        /// </summary>
        internal static string Enums_MeanType_Harmonic {
            get {
                return ResourceManager.GetString("Enums_MeanType_Harmonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heronian.
        /// </summary>
        internal static string Enums_MeanType_Heronian {
            get {
                return ResourceManager.GetString("Enums_MeanType_Heronian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum.
        /// </summary>
        internal static string Enums_MeanType_Maximum {
            get {
                return ResourceManager.GetString("Enums_MeanType_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to median.
        /// </summary>
        internal static string Enums_MeanType_Median {
            get {
                return ResourceManager.GetString("Enums_MeanType_Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum.
        /// </summary>
        internal static string Enums_MeanType_Minimum {
            get {
                return ResourceManager.GetString("Enums_MeanType_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadaraya-Watson.
        /// </summary>
        internal static string Enums_MeanType_NadarayaWatson {
            get {
                return ResourceManager.GetString("Enums_MeanType_NadarayaWatson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NN.
        /// </summary>
        internal static string Enums_MeanType_NN {
            get {
                return ResourceManager.GetString("Enums_MeanType_NN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMA.
        /// </summary>
        internal static string Enums_MeanType_SMA {
            get {
                return ResourceManager.GetString("Enums_MeanType_SMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tolerance.
        /// </summary>
        internal static string Enums_MeanType_Tolerance {
            get {
                return ResourceManager.GetString("Enums_MeanType_Tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noise coursing.
        /// </summary>
        internal static string Enums_NadarayaWatsonVariant_NoiseCoursing {
            get {
                return ResourceManager.GetString("Enums_NadarayaWatsonVariant_NoiseCoursing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to substitution.
        /// </summary>
        internal static string Enums_NadarayaWatsonVariant_Subsitution {
            get {
                return ResourceManager.GetString("Enums_NadarayaWatsonVariant_Subsitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addition.
        /// </summary>
        internal static string Enums_Operations_Addition {
            get {
                return ResourceManager.GetString("Enums_Operations_Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to constant.
        /// </summary>
        internal static string Enums_Operations_Constant {
            get {
                return ResourceManager.GetString("Enums_Operations_Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to division.
        /// </summary>
        internal static string Enums_Operations_Division {
            get {
                return ResourceManager.GetString("Enums_Operations_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exponentiation.
        /// </summary>
        internal static string Enums_Operations_Exponentiation {
            get {
                return ResourceManager.GetString("Enums_Operations_Exponentiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logarithmic.
        /// </summary>
        internal static string Enums_Operations_Logarithmic {
            get {
                return ResourceManager.GetString("Enums_Operations_Logarithmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiplication.
        /// </summary>
        internal static string Enums_Operations_Multiplication {
            get {
                return ResourceManager.GetString("Enums_Operations_Multiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to negative.
        /// </summary>
        internal static string Enums_Operations_Negative {
            get {
                return ResourceManager.GetString("Enums_Operations_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to positive.
        /// </summary>
        internal static string Enums_Operations_Positive {
            get {
                return ResourceManager.GetString("Enums_Operations_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rooting.
        /// </summary>
        internal static string Enums_Operations_Rooting {
            get {
                return ResourceManager.GetString("Enums_Operations_Rooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to substraction.
        /// </summary>
        internal static string Enums_Operations_Substraction {
            get {
                return ResourceManager.GetString("Enums_Operations_Substraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peek.
        /// </summary>
        internal static string Enums_Phenomenon_Peek {
            get {
                return ResourceManager.GetString("Enums_Phenomenon_Peek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saturation.
        /// </summary>
        internal static string Enums_Phenomenon_Saturation {
            get {
                return ResourceManager.GetString("Enums_Phenomenon_Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        internal static string Enums_StandardMeanVariant_Offset {
            get {
                return ResourceManager.GetString("Enums_StandardMeanVariant_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to straight.
        /// </summary>
        internal static string Enums_StandardMeanVariant_Straight {
            get {
                return ResourceManager.GetString("Enums_StandardMeanVariant_Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid previewer.
        /// </summary>
        internal static string GridPreviewer_Form_Text {
            get {
                return ResourceManager.GetString("GridPreviewer_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string GridPreviewer_Ui_Dataset_Index {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Dataset_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset.
        /// </summary>
        internal static string GridPreviewer_Ui_Dataset_Title {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Dataset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSizeColumnsMode:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_AutoSizeColumnsMode {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_AutoSizeColumnsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset grid.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_DatasetGrid {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_DatasetGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End index:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_EndIndex {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_EndIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast edit.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_FastEdit {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_FastEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_ChangesSaved {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Previewer loaded.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_GridPreviewerLoaded {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_GridPreviewerLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user value.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_InvalidUserValue {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_InvalidUserValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation rejected.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_OperationRejected {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_OperationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation revoked.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_OperationRevoked {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_OperationRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performed &amp; refreshed.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_PerformedAndRefreshed {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_PerformedAndRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values restored.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_ValuesRestored {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_ValuesRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_OK {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation type:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_OperationType {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Perform {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Perform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Refresh {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Reset {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Save {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start index:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_StartIndex {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addend:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Addend {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Addend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basis:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Basis {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Basis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisor:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Divisor {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Divisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponent:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Exponent {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Exponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplier:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Multiplier {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Multiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_NotApplicable {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtrahend:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Subtrahend {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Subtrahend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Value {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart not repainted.
        /// </summary>
        internal static string GridPreviewer_Ui_Preview_Info_ChartNotRepainted {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Preview_Info_ChartNotRepainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart refreshed.
        /// </summary>
        internal static string GridPreviewer_Ui_Preview_Info_ChartRefreshed {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Preview_Info_ChartRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart refresh error.
        /// </summary>
        internal static string GridPreviewer_Ui_Preview_Info_ChartRefreshError {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Preview_Info_ChartRefreshError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string GridPreviewer_Ui_Preview_Title {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Preview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language selector.
        /// </summary>
        internal static string LangSelector_Form_Text {
            get {
                return ResourceManager.GetString("LangSelector_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string LangSelector_Ui_Down_OkButton {
            get {
                return ResourceManager.GetString("LangSelector_Ui_Down_OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string MainWindow_Menu_Chart_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Chart_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string MainWindow_Menu_Chart_Title {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Chart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        internal static string MainWindow_Menu_File_Import {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MainWindow_Menu_File_Title {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaging info.
        /// </summary>
        internal static string MainWindow_Menu_Means_AveragingInfo {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means_AveragingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string MainWindow_Menu_Means_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Means.
        /// </summary>
        internal static string MainWindow_Menu_Means_Title {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string MainWindow_Menu_Panel_Hide {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep proportions.
        /// </summary>
        internal static string MainWindow_Menu_Panel_KeepProportions {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_KeepProportions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string MainWindow_Menu_Panel_Lock {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        internal static string MainWindow_Menu_Panel_Title {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string MainWindow_Menu_Program_About {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MainWindow_Menu_Program_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language....
        /// </summary>
        internal static string MainWindow_Menu_Program_SelectLanguage {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical analysis....
        /// </summary>
        internal static string MainWindow_Menu_Program_StatisticalAnalysis {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_StatisticalAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string MainWindow_Menu_Program_Title {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string MainWindow_Panel_Average_Apply {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Average_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaging &amp; smoothing.
        /// </summary>
        internal static string MainWindow_Panel_Average_Averaging {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Average_Averaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean type:.
        /// </summary>
        internal static string MainWindow_Panel_Average_MeanType {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Average_MeanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of curves:.
        /// </summary>
        internal static string MainWindow_Panel_Average_NumberOfCurves2 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Average_NumberOfCurves2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard deviation:.
        /// </summary>
        internal static string MainWindow_Panel_Average_StandardDeviation1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Average_StandardDeviation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string MainWindow_Panel_Average_Title {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Average_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve scaffold:.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_CurveScaffold1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_CurveScaffold1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hyperbolic.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_CurveScaffold2_Hyperbolic {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_CurveScaffold2_Hyperbolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not chosen.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_CurveScaffold2_NotChosen {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_CurveScaffold2_NotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polynomial.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_CurveScaffold2_Polynomial {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_CurveScaffold2_Polynomial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waveform.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_CurveScaffold2_Waveform {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_CurveScaffold2_Waveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole set of curves.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_CurvesSet {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_CurvesSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval points:.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_Density {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending X point:.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_EndingXPoint {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_EndingXPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate set.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_GenerateSet {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_GenerateSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern curve scaffold.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_IdealCurveScaffold {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_IdealCurveScaffold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of curves:.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_NumberOfCurves1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_NumberOfCurves1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting X point:.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_StartingXPoint {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_StartingXPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_Title {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve index:.
        /// </summary>
        internal static string MainWindow_Panel_Modified_CurveIndex {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_CurveIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of curves:.
        /// </summary>
        internal static string MainWindow_Panel_Modified_CurvesNumber {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_CurvesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve type:.
        /// </summary>
        internal static string MainWindow_Panel_Modified_CurveType {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_CurveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset control.
        /// </summary>
        internal static string MainWindow_Panel_Modified_DatasetControl {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_DatasetControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian noise.
        /// </summary>
        internal static string MainWindow_Panel_Modified_GaussianNoise {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_GaussianNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malform.
        /// </summary>
        internal static string MainWindow_Panel_Modified_Malform {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_Malform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dataset.
        /// </summary>
        internal static string MainWindow_Panel_Modified_ShowDataSet {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_ShowDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrounding:.
        /// </summary>
        internal static string MainWindow_Panel_Modified_Surrounding {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_Surrounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string MainWindow_Panel_Modified_Title {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer&apos;s thesis.
        /// </summary>
        internal static string MainWindow_Ui_Form_Text {
            get {
                return ResourceManager.GetString("MainWindow_Ui_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Means settings.
        /// </summary>
        internal static string MeansSettings_Form_Text {
            get {
                return ResourceManager.GetString("MeansSettings_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic-geometric mean (AGM).
        /// </summary>
        internal static string MeansSettings_Ui_AGM {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_AGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        internal static string MeansSettings_Ui_Amount {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central method.
        /// </summary>
        internal static string MeansSettings_Ui_Central {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finisher function:.
        /// </summary>
        internal static string MeansSettings_Ui_FinisherFunction {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_FinisherFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generalized (power) mean.
        /// </summary>
        internal static string MeansSettings_Ui_Generalized {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Generalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric mean.
        /// </summary>
        internal static string MeansSettings_Ui_Geometric {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Geometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic mean.
        /// </summary>
        internal static string MeansSettings_Ui_Harmonic {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Harmonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heronian mean.
        /// </summary>
        internal static string MeansSettings_Ui_Heronian {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Heronian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel size:.
        /// </summary>
        internal static string MeansSettings_Ui_KernelSize {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_KernelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel type:.
        /// </summary>
        internal static string MeansSettings_Ui_KernelType {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_KernelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass percent:.
        /// </summary>
        internal static string MeansSettings_Ui_MassPercent {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_MassPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadaraya-Watson kernel-weighted average.
        /// </summary>
        internal static string MeansSettings_Ui_NadarayaWatson {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_NadarayaWatson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Neighbors smoothing.
        /// </summary>
        internal static string MeansSettings_Ui_NN {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_NN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MeansSettings_Ui_OK {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank:.
        /// </summary>
        internal static string MeansSettings_Ui_Rank {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance method.
        /// </summary>
        internal static string MeansSettings_Ui_ToleranceHeader {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_ToleranceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance:.
        /// </summary>
        internal static string MeansSettings_Ui_ToleranceText {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_ToleranceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant:.
        /// </summary>
        internal static string MeansSettings_Ui_Variant {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocation error.
        /// </summary>
        internal static string Messages_General_OutOfMemoryException_Caption {
            get {
                return ResourceManager.GetString("Messages_General_OutOfMemoryException_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception of type OutOfMemoryException has been thrown. This happens when there is no enough memory to continue the execution of a program..
        /// </summary>
        internal static string Messages_General_OutOfMemoryException_Text {
            get {
                return ResourceManager.GetString("Messages_General_OutOfMemoryException_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation.
        /// </summary>
        internal static string Messages_GridPreviewer_ChartRefreshing_Caption {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_ChartRefreshing_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart refreshing error, possibly recalculating axes scales (too large to display)..
        /// </summary>
        internal static string Messages_GridPreviewer_ChartRefreshing_Text {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_ChartRefreshing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong cast, conversion or format.
        /// </summary>
        internal static string Messages_GridPreviewer_ImproperUserValue_Caption {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_ImproperUserValue_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given value is improper. Note, that numbers should be localized in accord with your operating system current regional settings..
        /// </summary>
        internal static string Messages_GridPreviewer_ImproperUserValue_Text {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_ImproperUserValue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improper index value.
        /// </summary>
        internal static string Messages_GridPreviewer_IndexGreaterThanAllowed_Caption {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_IndexGreaterThanAllowed_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified index would be greater than allowed. Change rejected..
        /// </summary>
        internal static string Messages_GridPreviewer_IndexGreaterThanAllowed_Text {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_IndexGreaterThanAllowed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improper index value.
        /// </summary>
        internal static string Messages_GridPreviewer_IndexLowerThanAllowed_Caption {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_IndexLowerThanAllowed_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified index would be lower than allowed. Change revoked..
        /// </summary>
        internal static string Messages_GridPreviewer_IndexLowerThanAllowed_Text {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_IndexLowerThanAllowed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid curve points.
        /// </summary>
        internal static string Messages_GridPreviewer_InvalidCurvePoints_Caption {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_InvalidCurvePoints_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of points value is too large or improper to be displayed on a chart..
        /// </summary>
        internal static string Messages_GridPreviewer_InvalidCurvePoints_Text {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_InvalidCurvePoints_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during calculation.
        /// </summary>
        internal static string Messages_GridPreviewer_PerformOperation_Caption {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_PerformOperation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate values for all specified arguments. Overflow. Changes rejected..
        /// </summary>
        internal static string Messages_GridPreviewer_PerformOperation_Text {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_PerformOperation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidated data.
        /// </summary>
        internal static string Messages_MainWindow_ChartRefreshing_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_ChartRefreshing_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occured when trying to refresh a chart or recalculating axes scales..
        /// </summary>
        internal static string Messages_MainWindow_ChartRefreshing_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_ChartRefreshing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data set imported.
        /// </summary>
        internal static string Messages_MainWindow_CurveDataSetImported_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_CurveDataSetImported_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data set file has been successfully imported..
        /// </summary>
        internal static string Messages_MainWindow_CurveDataSetImported_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_CurveDataSetImported_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisite not matched.
        /// </summary>
        internal static string Messages_MainWindow_CurveTypeNotSelected_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_CurveTypeNotSelected_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose a curve type from &apos;Dataset control&apos; section..
        /// </summary>
        internal static string Messages_MainWindow_CurveTypeNotSelected_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_CurveTypeNotSelected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported operation.
        /// </summary>
        internal static string Messages_MainWindow_OperationMalformRejected_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_OperationMalformRejected_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results of this operation was rejected due to improper values..
        /// </summary>
        internal static string Messages_MainWindow_OperationMalformRejected_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_OperationMalformRejected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisite not matched.
        /// </summary>
        internal static string Messages_MainWindow_PatternCurveNotChosen_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_PatternCurveNotChosen_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern curve scaffold has not been chosen..
        /// </summary>
        internal static string Messages_MainWindow_PatternCurveNotChosen_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_PatternCurveNotChosen_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating points warning.
        /// </summary>
        internal static string Messages_MainWindow_PointsNotValidToChart_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_PointsNotValidToChart_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the generated points are not valid to display them on a chart. Those points will be removed from the set..
        /// </summary>
        internal static string Messages_MainWindow_PointsNotValidToChart_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_PointsNotValidToChart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data selection problem.
        /// </summary>
        internal static string Messages_MainWindow_SeriesSelection_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_SeriesSelection_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any curve has not been generated yet..
        /// </summary>
        internal static string Messages_MainWindow_SeriesSelection_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_SeriesSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid curve index.
        /// </summary>
        internal static string Messages_MainWindow_SpecifiedCurveDoesNotExist_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_SpecifiedCurveDoesNotExist_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified curve data doesn&apos;t exist..
        /// </summary>
        internal static string Messages_MainWindow_SpecifiedCurveDoesNotExist_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_SpecifiedCurveDoesNotExist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported importing error.
        /// </summary>
        internal static string Messages_MainWindow_UnsupportedImportingError_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_UnsupportedImportingError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during importing curves data sets. See log to gain more informations..
        /// </summary>
        internal static string Messages_MainWindow_UnsupportedImportingError_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_UnsupportedImportingError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported mean type.
        /// </summary>
        internal static string Messages_MeansSettings_NotSupportedFinisherFunction_Caption {
            get {
                return ResourceManager.GetString("Messages_MeansSettings_NotSupportedFinisherFunction_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen mean type is not allowed for this averaging method..
        /// </summary>
        internal static string Messages_MeansSettings_NotSupportedFinisherFunction_Text {
            get {
                return ResourceManager.GetString("Messages_MeansSettings_NotSupportedFinisherFunction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data selection problem.
        /// </summary>
        internal static string Messages_StatisticalAnalysis_PointsNotValidToChart_Caption {
            get {
                return ResourceManager.GetString("Messages_StatisticalAnalysis_PointsNotValidToChart_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some points cannot be shown on a chart. The chart will not be refreshed..
        /// </summary>
        internal static string Messages_StatisticalAnalysis_PointsNotValidToChart_Text {
            get {
                return ResourceManager.GetString("Messages_StatisticalAnalysis_PointsNotValidToChart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized error.
        /// </summary>
        internal static string Messages_StatisticalAnalysis_Unrecognized_Caption {
            get {
                return ResourceManager.GetString("Messages_StatisticalAnalysis_Unrecognized_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unkown error has occured while refreshing chart..
        /// </summary>
        internal static string Messages_StatisticalAnalysis_Unrecognized_Text {
            get {
                return ResourceManager.GetString("Messages_StatisticalAnalysis_Unrecognized_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of range.
        /// </summary>
        internal static string Messages_StatisticalAnalysis_ValueOutOfRange_Caption {
            get {
                return ResourceManager.GetString("Messages_StatisticalAnalysis_ValueOutOfRange_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided value is not within a specified range..
        /// </summary>
        internal static string Messages_StatisticalAnalysis_ValueOutOfRange_Text {
            get {
                return ResourceManager.GetString("Messages_StatisticalAnalysis_ValueOutOfRange_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern curve definer.
        /// </summary>
        internal static string PatternCurveDefiner_Form_Text {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Hyperbolic_Bound_ac {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Hyperbolic_Bound_ac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Hyperbolic_Bound_bd {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Hyperbolic_Bound_bd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbolic.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Hyperbolic_Hyperbolic {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Hyperbolic_Hyperbolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Hyperbolic_Parameters {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Hyperbolic_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Polynomial_Parameters {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Polynomial_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polynomial.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Polynomial_Polynomial {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Polynomial_Polynomial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Parameters {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sawtooth.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Sawtooth {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Sawtooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sine.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Sine {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Sine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Square {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to triangle.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Triangle {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Triangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waveform.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Waveform {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Waveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavetype.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_WaveType {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_WaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string PatternCurveDefiner_Ui_Cancel {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Ui_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PatternCurveDefiner_Ui_OK {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Ui_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical analysis.
        /// </summary>
        internal static string StatisticalAnalysis_Form_Text {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Chart {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve index:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_CurveIndex {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_CurveIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve type:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_CurveType {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_CurveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Dataset {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_DatasetSelection {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_DatasetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean type:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_MeanType {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_MeanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Noise {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phenomenon:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Phenomenon {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Phenomenon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Title {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_Noise {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peek.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_Peek {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_Peek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_Saturation {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard deviation.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_Title {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_Title", resourceCulture);
            }
        }
    }
}
