//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pl_PL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pl_PL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PI.Locales.pl-PL", typeof(pl_PL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia arytmetyczno-geometryczna jest zdefiniowana następująco:.
        /// </summary>
        internal static string AveragingInfo_AGM_TextBox1Text {
            get {
                return ResourceManager.GetString("AveragingInfo_AGM_TextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostało to zmienione na:.
        /// </summary>
        internal static string AveragingInfo_AGM_TextBox2Text {
            get {
                return ResourceManager.GetString("AveragingInfo_AGM_TextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podejście metody Własnej-Różnicowej prezentuje się następująco:.
        /// </summary>
        internal static string AveragingInfo_CustomDifferential_TextBox1Text {
            get {
                return ResourceManager.GetString("AveragingInfo_CustomDifferential_TextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma to swoją alternatywną wersję, czyli:.
        /// </summary>
        internal static string AveragingInfo_CustomDifferential_TextBox2Text {
            get {
                return ResourceManager.GetString("AveragingInfo_CustomDifferential_TextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia geometryczna jest zdefiniowana następująco:.
        /// </summary>
        internal static string AveragingInfo_CustomGeometric_TextBox1Text {
            get {
                return ResourceManager.GetString("AveragingInfo_CustomGeometric_TextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostało to zamienione na:.
        /// </summary>
        internal static string AveragingInfo_CustomGeometric_TextBox2Text {
            get {
                return ResourceManager.GetString("AveragingInfo_CustomGeometric_TextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podejście metody Własnej-Tolerującej filtruje wartości wykorzystując komparator (M jest medianą lub średnią arytmetyczną):.
        /// </summary>
        internal static string AveragingInfo_CustomTolerance_TextBox1Text {
            get {
                return ResourceManager.GetString("AveragingInfo_CustomTolerance_TextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komparator jest używany do klasyfikowania wartości, które będą przetwarzane w dalszym etapie (FUNC jest średnią kończącą):.
        /// </summary>
        internal static string AveragingInfo_CustomTolerance_TextBox2Text {
            get {
                return ResourceManager.GetString("AveragingInfo_CustomTolerance_TextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykładnicza średnia krocząca jest zdefiniowana następująco:.
        /// </summary>
        internal static string AveragingInfo_EMA_TextBox1Text {
            get {
                return ResourceManager.GetString("AveragingInfo_EMA_TextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostało to zmienione na:.
        /// </summary>
        internal static string AveragingInfo_EMA_TextBox2Text {
            get {
                return ResourceManager.GetString("AveragingInfo_EMA_TextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje o uśrednianiu.
        /// </summary>
        internal static string AveragingInfo_Form_Text {
            get {
                return ResourceManager.GetString("AveragingInfo_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia geometryczna jest zdefiniowana następująco:.
        /// </summary>
        internal static string AveragingInfo_Geometric_TextBox1Text {
            get {
                return ResourceManager.GetString("AveragingInfo_Geometric_TextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostało to zmienione na:.
        /// </summary>
        internal static string AveragingInfo_Geometric_TextBox2Text {
            get {
                return ResourceManager.GetString("AveragingInfo_Geometric_TextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia harmoniczna jest określona dla liczb rzeczywistych dodatnich następująco:.
        /// </summary>
        internal static string AveragingInfo_Harmonic_TextBox1Text {
            get {
                return ResourceManager.GetString("AveragingInfo_Harmonic_TextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie zostało to zmienione, jednakże może być wyrażone również jako:.
        /// </summary>
        internal static string AveragingInfo_Harmonic_TextBox2Text {
            get {
                return ResourceManager.GetString("AveragingInfo_Harmonic_TextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia Herona w geometrii jest zdefiniowana następująco:.
        /// </summary>
        internal static string AveragingInfo_Heronian_TextBox1Text {
            get {
                return ResourceManager.GetString("AveragingInfo_Heronian_TextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostało to zmienione na:.
        /// </summary>
        internal static string AveragingInfo_Heronian_TextBox2Text {
            get {
                return ResourceManager.GetString("AveragingInfo_Heronian_TextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardowa średnia ważona jest określona następująco:.
        /// </summary>
        internal static string AveragingInfo_LnWages_TextBox1Text {
            get {
                return ResourceManager.GetString("AveragingInfo_LnWages_TextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostało to zamienione na średnią ważoną logarytmicznie, jak poniżej:.
        /// </summary>
        internal static string AveragingInfo_LnWages_TextBox2Text {
            get {
                return ResourceManager.GetString("AveragingInfo_LnWages_TextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia logarytmiczna jest zdefiniowana następująco:.
        /// </summary>
        internal static string AveragingInfo_Logarithmic_TextBox1Text {
            get {
                return ResourceManager.GetString("AveragingInfo_Logarithmic_TextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostało to zmienione na:.
        /// </summary>
        internal static string AveragingInfo_Logarithmic_TextBox2Text {
            get {
                return ResourceManager.GetString("AveragingInfo_Logarithmic_TextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia potęgowa jest zdefiniowana dla określonego rzędu k jak poniżej:.
        /// </summary>
        internal static string AveragingInfo_Power_TextBox1Text {
            get {
                return ResourceManager.GetString("AveragingInfo_Power_TextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie zostało to zmienione, jednak domyślnym rzędem k jest:.
        /// </summary>
        internal static string AveragingInfo_Power_TextBox2Text {
            get {
                return ResourceManager.GetString("AveragingInfo_Power_TextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia kwadratowa jest zdefiniowana następująco:.
        /// </summary>
        internal static string AveragingInfo_RMS_TextBox1Text {
            get {
                return ResourceManager.GetString("AveragingInfo_RMS_TextBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jest to obliczane z użyciem średniej potęgowej w postaci jak poniżej:.
        /// </summary>
        internal static string AveragingInfo_RMS_TextBox2Text {
            get {
                return ResourceManager.GetString("AveragingInfo_RMS_TextBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia wykresu.
        /// </summary>
        internal static string ChartSettings_Form_Text {
            get {
                return ResourceManager.GetString("ChartSettings_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastosuj do krzywej:.
        /// </summary>
        internal static string ChartSettings_Ui_General_ApplyToCurve {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_General_ApplyToCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ChartSettings_Ui_General_OK {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_General_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykres.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_Chart_Title {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_Chart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osie.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_ChartArea_Axes {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_ChartArea_Axes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obszar wykresu.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_ChartArea_ChartArea {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_ChartArea_ChartArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obszar wykresu.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_ChartArea_Title {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_ChartArea_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie danych.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_Series_Title {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_Series_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wszystkie.
        /// </summary>
        internal static string Enums_ApplyToCurve_All {
            get {
                return ResourceManager.GetString("Enums_ApplyToCurve_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uśredniona.
        /// </summary>
        internal static string Enums_ApplyToCurve_Average {
            get {
                return ResourceManager.GetString("Enums_ApplyToCurve_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wygenerowana.
        /// </summary>
        internal static string Enums_ApplyToCurve_Generated {
            get {
                return ResourceManager.GetString("Enums_ApplyToCurve_Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wzorcowa.
        /// </summary>
        internal static string Enums_ApplyToCurve_Pattern {
            get {
                return ResourceManager.GetString("Enums_ApplyToCurve_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arytm.-geom..
        /// </summary>
        internal static string Enums_AvgInfo_Tabs_AGM {
            get {
                return ResourceManager.GetString("Enums_AvgInfo_Tabs_AGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to własna-różnicowa.
        /// </summary>
        internal static string Enums_AvgInfo_Tabs_CustomDifferential {
            get {
                return ResourceManager.GetString("Enums_AvgInfo_Tabs_CustomDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to własna-geom..
        /// </summary>
        internal static string Enums_AvgInfo_Tabs_CustomGeometric {
            get {
                return ResourceManager.GetString("Enums_AvgInfo_Tabs_CustomGeometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to własna-tolerująca.
        /// </summary>
        internal static string Enums_AvgInfo_Tabs_CustomTolerance {
            get {
                return ResourceManager.GetString("Enums_AvgInfo_Tabs_CustomTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to krocząca.
        /// </summary>
        internal static string Enums_AvgInfo_Tabs_EMA {
            get {
                return ResourceManager.GetString("Enums_AvgInfo_Tabs_EMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geometryczna.
        /// </summary>
        internal static string Enums_AvgInfo_Tabs_Geometric {
            get {
                return ResourceManager.GetString("Enums_AvgInfo_Tabs_Geometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to harmoniczna.
        /// </summary>
        internal static string Enums_AvgInfo_Tabs_Harmonic {
            get {
                return ResourceManager.GetString("Enums_AvgInfo_Tabs_Harmonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herona.
        /// </summary>
        internal static string Enums_AvgInfo_Tabs_Heronian {
            get {
                return ResourceManager.GetString("Enums_AvgInfo_Tabs_Heronian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log. ważona.
        /// </summary>
        internal static string Enums_AvgInfo_Tabs_LnWages {
            get {
                return ResourceManager.GetString("Enums_AvgInfo_Tabs_LnWages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logarytmiczna.
        /// </summary>
        internal static string Enums_AvgInfo_Tabs_Logarithmic {
            get {
                return ResourceManager.GetString("Enums_AvgInfo_Tabs_Logarithmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to potęgowa.
        /// </summary>
        internal static string Enums_AvgInfo_Tabs_Power {
            get {
                return ResourceManager.GetString("Enums_AvgInfo_Tabs_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kwadratowa.
        /// </summary>
        internal static string Enums_AvgInfo_Tabs_RMS {
            get {
                return ResourceManager.GetString("Enums_AvgInfo_Tabs_RMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mediana.
        /// </summary>
        internal static string Enums_CustomDifferentialMeanMode_Mediana {
            get {
                return ResourceManager.GetString("Enums_CustomDifferentialMeanMode_Mediana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suma.
        /// </summary>
        internal static string Enums_CustomDifferentialMeanMode_Sum {
            get {
                return ResourceManager.GetString("Enums_CustomDifferentialMeanMode_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to średnia arytmetyczna.
        /// </summary>
        internal static string Enums_CustomToleranceComparerType_ArithmeticMean {
            get {
                return ResourceManager.GetString("Enums_CustomToleranceComparerType_ArithmeticMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mediana.
        /// </summary>
        internal static string Enums_CustomToleranceComparerType_Mediana {
            get {
                return ResourceManager.GetString("Enums_CustomToleranceComparerType_Mediana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to średnia arytmetyczna.
        /// </summary>
        internal static string Enums_CustomToleranceFinisherFunctions_ArithmeticMean {
            get {
                return ResourceManager.GetString("Enums_CustomToleranceFinisherFunctions_ArithmeticMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to średnia geometryczna.
        /// </summary>
        internal static string Enums_CustomToleranceFinisherFunctions_GeometricMean {
            get {
                return ResourceManager.GetString("Enums_CustomToleranceFinisherFunctions_GeometricMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maksimum.
        /// </summary>
        internal static string Enums_CustomToleranceFinisherFunctions_Maximum {
            get {
                return ResourceManager.GetString("Enums_CustomToleranceFinisherFunctions_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mediana.
        /// </summary>
        internal static string Enums_CustomToleranceFinisherFunctions_Mediana {
            get {
                return ResourceManager.GetString("Enums_CustomToleranceFinisherFunctions_Mediana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum.
        /// </summary>
        internal static string Enums_CustomToleranceFinisherFunctions_Minimum {
            get {
                return ResourceManager.GetString("Enums_CustomToleranceFinisherFunctions_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uśredniona.
        /// </summary>
        internal static string Enums_DataSetCurvesTypes_Average {
            get {
                return ResourceManager.GetString("Enums_DataSetCurvesTypes_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wygenerowana.
        /// </summary>
        internal static string Enums_DataSetCurvesTypes_Generated {
            get {
                return ResourceManager.GetString("Enums_DataSetCurvesTypes_Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wzorcowa.
        /// </summary>
        internal static string Enums_DataSetCurvesTypes_Pattern {
            get {
                return ResourceManager.GetString("Enums_DataSetCurvesTypes_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arytm.-geom..
        /// </summary>
        internal static string Enums_MeanTypes_AGM {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_AGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arytmetyczna.
        /// </summary>
        internal static string Enums_MeanTypes_Arithmetic {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Arithmetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to własna-różnicowa.
        /// </summary>
        internal static string Enums_MeanTypes_CustomDifferential {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_CustomDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to własna-tolerująca.
        /// </summary>
        internal static string Enums_MeanTypes_CustomTolerance {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_CustomTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to krocząca.
        /// </summary>
        internal static string Enums_MeanTypes_EMA {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_EMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geometryczna-parzystość.
        /// </summary>
        internal static string Enums_MeanTypes_GeometricOfParity {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_GeometricOfParity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geometryczna-znak.
        /// </summary>
        internal static string Enums_MeanTypes_GeometricOfSign {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_GeometricOfSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to harmoniczna.
        /// </summary>
        internal static string Enums_MeanTypes_Harmonic {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Harmonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herona.
        /// </summary>
        internal static string Enums_MeanTypes_Heronian {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Heronian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log. ważona.
        /// </summary>
        internal static string Enums_MeanTypes_LnWages {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_LnWages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logarytmiczna.
        /// </summary>
        internal static string Enums_MeanTypes_Logarithmic {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Logarithmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maksimum.
        /// </summary>
        internal static string Enums_MeanTypes_Maximum {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mediana.
        /// </summary>
        internal static string Enums_MeanTypes_Mediana {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Mediana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum.
        /// </summary>
        internal static string Enums_MeanTypes_Minimum {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to potęgowa.
        /// </summary>
        internal static string Enums_MeanTypes_Power {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kwadratowa.
        /// </summary>
        internal static string Enums_MeanTypes_RMS {
            get {
                return ResourceManager.GetString("Enums_MeanTypes_RMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dodawanie.
        /// </summary>
        internal static string Enums_Operations_Addition {
            get {
                return ResourceManager.GetString("Enums_Operations_Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stała.
        /// </summary>
        internal static string Enums_Operations_Constant {
            get {
                return ResourceManager.GetString("Enums_Operations_Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dzielenie.
        /// </summary>
        internal static string Enums_Operations_Division {
            get {
                return ResourceManager.GetString("Enums_Operations_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to potęgowanie.
        /// </summary>
        internal static string Enums_Operations_Exponentiation {
            get {
                return ResourceManager.GetString("Enums_Operations_Exponentiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logarytmowanie.
        /// </summary>
        internal static string Enums_Operations_Logarithmic {
            get {
                return ResourceManager.GetString("Enums_Operations_Logarithmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mnożenie.
        /// </summary>
        internal static string Enums_Operations_Multiplication {
            get {
                return ResourceManager.GetString("Enums_Operations_Multiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ujemny znak.
        /// </summary>
        internal static string Enums_Operations_Negative {
            get {
                return ResourceManager.GetString("Enums_Operations_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dodatni znak.
        /// </summary>
        internal static string Enums_Operations_Positive {
            get {
                return ResourceManager.GetString("Enums_Operations_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pierwiastkowanie.
        /// </summary>
        internal static string Enums_Operations_Rooting {
            get {
                return ResourceManager.GetString("Enums_Operations_Rooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odejmowanie.
        /// </summary>
        internal static string Enums_Operations_Substraction {
            get {
                return ResourceManager.GetString("Enums_Operations_Substraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deformacja.
        /// </summary>
        internal static string Enums_PhenomenonIndex_Deformation {
            get {
                return ResourceManager.GetString("Enums_PhenomenonIndex_Deformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pik.
        /// </summary>
        internal static string Enums_PhenomenonIndex_Peek {
            get {
                return ResourceManager.GetString("Enums_PhenomenonIndex_Peek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zestaw danych.
        /// </summary>
        internal static string GridPreviewer_Ui_Dataset_Dataset {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Dataset_Dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siatka podglądu danych.
        /// </summary>
        internal static string GridPreviewer_Ui_Form_Text {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSizeColumnsMode:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_AutoSizeColumnsMode {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_AutoSizeColumnsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siatka zestawu danych.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_DatasetGrid {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_DatasetGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks końca:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_EndIndex {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_EndIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szybka edycja.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_FastEdit {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_FastEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiany zapisane.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_ChangesSaved {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siatka załadowana.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_GridPreviewerLoaded {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_GridPreviewerLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieważna wartość użytkownika.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_InvalidUserValue {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_InvalidUserValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacja odrzucona.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_OperationRejected {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_OperationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacja wycofana.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_OperationRevoked {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_OperationRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonano i odświeżono.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_PerformedAndRefreshed {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_PerformedAndRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartości odzyskane.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_ValuesRestored {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_ValuesRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_OK {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ operacji:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_OperationType {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonaj.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Perform {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Perform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odśwież.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Refresh {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przywróć.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Reset {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Save {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks początku:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_StartIndex {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajnik:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Addend {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Addend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawa:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Basis {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Basis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podzielnik:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Divisor {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Divisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykładnik:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Exponent {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Exponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnożnik:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Multiplier {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Multiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/D:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_NotApplicable {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjemnik:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Subtrahend {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Subtrahend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Value {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykres nieodświeżony.
        /// </summary>
        internal static string GridPreviewer_Ui_Preview_Info_ChartNotRepainted {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Preview_Info_ChartNotRepainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykres odświeżono.
        /// </summary>
        internal static string GridPreviewer_Ui_Preview_Info_ChartRefreshed {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Preview_Info_ChartRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd odświeżania wykresu.
        /// </summary>
        internal static string GridPreviewer_Ui_Preview_Info_ChartRefreshError {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Preview_Info_ChartRefreshError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd.
        /// </summary>
        internal static string GridPreviewer_Ui_Preview_Preview {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Preview_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angielski.
        /// </summary>
        internal static string LangSelector_Languages_English {
            get {
                return ResourceManager.GetString("LangSelector_Languages_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polski.
        /// </summary>
        internal static string LangSelector_Languages_Polish {
            get {
                return ResourceManager.GetString("LangSelector_Languages_Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string LangSelector_Ui_Down_OkBtn {
            get {
                return ResourceManager.GetString("LangSelector_Ui_Down_OkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybór języka.
        /// </summary>
        internal static string LangSelector_Ui_Form_Text {
            get {
                return ResourceManager.GetString("LangSelector_Ui_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykres.
        /// </summary>
        internal static string MainWindow_Menu_Chart {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        internal static string MainWindow_Menu_Chart_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Chart_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uśrednianie.
        /// </summary>
        internal static string MainWindow_Menu_Means {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje.
        /// </summary>
        internal static string MainWindow_Menu_Means_AveragingInfo {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means_AveragingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        internal static string MainWindow_Menu_Means_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        internal static string MainWindow_Menu_Panel {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukryj.
        /// </summary>
        internal static string MainWindow_Menu_Panel_Hide {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utrzymuj wymiary.
        /// </summary>
        internal static string MainWindow_Menu_Panel_KeepProportions {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_KeepProportions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zablokuj.
        /// </summary>
        internal static string MainWindow_Menu_Panel_Lock {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string MainWindow_Menu_Program {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończ.
        /// </summary>
        internal static string MainWindow_Menu_Program_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz język.
        /// </summary>
        internal static string MainWindow_Menu_Program_SelectLanguage {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analiza statystyczna.
        /// </summary>
        internal static string MainWindow_Menu_Program_StatisticalAnalysis {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_StatisticalAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks krzywej:.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_CurveIndex {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_CurveIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość krzywych:.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_CurvesNumber {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_CurvesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ krzywej:.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_CurveType {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_CurveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrola zestawem danych.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_DatasetControl {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_DatasetControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szum Gaussa.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_GaussianNoise {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_GaussianNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zniekształć.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_Malform {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_Malform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż zestaw danych.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_ShowDataSet {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_ShowDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otoczenie:.
        /// </summary>
        internal static string MainWindow_Panel_Datasheet_Surrounding {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Datasheet_Surrounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generowanie.
        /// </summary>
        internal static string MainWindow_Panel_Generate {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastosuj.
        /// </summary>
        internal static string MainWindow_Panel_Generate_Apply {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uśrednianie.
        /// </summary>
        internal static string MainWindow_Panel_Generate_Averaging {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_Averaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkielet krzywej:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_CurveScaffold1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_CurveScaffold1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hiperboliczny.
        /// </summary>
        internal static string MainWindow_Panel_Generate_CurveScaffold2_Hyperbolic {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_CurveScaffold2_Hyperbolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie wybrany.
        /// </summary>
        internal static string MainWindow_Panel_Generate_CurveScaffold2_NotChosen {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_CurveScaffold2_NotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wielomianowy.
        /// </summary>
        internal static string MainWindow_Panel_Generate_CurveScaffold2_Polynomial {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_CurveScaffold2_Polynomial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to falowy.
        /// </summary>
        internal static string MainWindow_Panel_Generate_CurveScaffold2_Waveform {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_CurveScaffold2_Waveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cały zestaw krzywych.
        /// </summary>
        internal static string MainWindow_Panel_Generate_CurvesSet {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_CurvesSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkty przedziału:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_Density {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Końcowy punkt x:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_EndingXPoint {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_EndingXPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygeneruj zestaw.
        /// </summary>
        internal static string MainWindow_Panel_Generate_GenerateSet {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_GenerateSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ średniej:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_MeanType {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_MeanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość krzywych:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_NumberOfCurves1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_NumberOfCurves1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość krzywych:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_NumberOfCurves2 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_NumberOfCurves2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkielet krzywej wzorcowej.
        /// </summary>
        internal static string MainWindow_Panel_Generate_PatternCurveScaffold {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_PatternCurveScaffold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odch. standardowe:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_StandardDeviation1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_StandardDeviation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Początkowy punkt x:.
        /// </summary>
        internal static string MainWindow_Panel_Generate_StartingXPoint {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Generate_StartingXPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string MainWindow_Panel_Program {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stan obecny:.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas:.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_Counts1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_Counts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework:.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_DotNetFramework {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_DotNetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porażka.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_Failure {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieznany.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_InfoObtainingErrorText {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_InfoObtainingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_Informations {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_Logging {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka logu:.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_LogPath1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_LogPath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja sys. oper.:.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_OsVersion1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_OsVersion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukces.
        /// </summary>
        internal static string MainWindow_Panel_Program_ActualState2_Success {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_ActualState2_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czasomierz.
        /// </summary>
        internal static string MainWindow_Panel_Program_Timer {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Program_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praca inżynierska.
        /// </summary>
        internal static string MainWindow_Ui_Form_Text {
            get {
                return ResourceManager.GetString("MainWindow_Ui_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia średnich.
        /// </summary>
        internal static string MeansSettings_Form_Text {
            get {
                return ResourceManager.GetString("MeansSettings_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Własna-różnicowa.
        /// </summary>
        internal static string MeansSettings_Ui_CustomDifferential_CustomDifferential {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_CustomDifferential_CustomDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryb pracy:.
        /// </summary>
        internal static string MeansSettings_Ui_CustomDifferential_DifferentialWorkMode {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_CustomDifferential_DifferentialWorkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komparator bloków MIN/MAX:.
        /// </summary>
        internal static string MeansSettings_Ui_CustomTolerance_Comparer {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_CustomTolerance_Comparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Własna-tolerująca.
        /// </summary>
        internal static string MeansSettings_Ui_CustomTolerance_CustomTolerance {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_CustomTolerance_CustomTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja kończąca:.
        /// </summary>
        internal static string MeansSettings_Ui_CustomTolerance_FinisherFunction {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_CustomTolerance_FinisherFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MeansSettings_Ui_CustomTolerance_OK {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_CustomTolerance_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerancja komparatora:.
        /// </summary>
        internal static string MeansSettings_Ui_CustomTolerance_Tolerance {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_CustomTolerance_Tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia potęgowa.
        /// </summary>
        internal static string MeansSettings_Ui_Power_Power {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Power_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rząd k:.
        /// </summary>
        internal static string MeansSettings_Ui_Power_PowRank {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Power_PowRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd alokacji pamięci.
        /// </summary>
        internal static string MessageBoxShower_General_OutOfMemoryExceptionStop_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_General_OutOfMemoryExceptionStop_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjątek typu OutOfMemoryException został rzucony. Dzieje się tak, kiedy nie wystarczającej ilości pamięci, aby kontynuować wykonywanie programu..
        /// </summary>
        internal static string MessageBoxShower_General_OutOfMemoryExceptionStop_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_General_OutOfMemoryExceptionStop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieważna operacja.
        /// </summary>
        internal static string MessageBoxShower_GridPreviewer_Chart_ChartRefreshingError_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_GridPreviewer_Chart_ChartRefreshingError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd odświeżania wykresu, najprawdopodobniej związany z ponownym obliczaniem skal osi (zbyt wielkie do wyświetlenia)..
        /// </summary>
        internal static string MessageBoxShower_GridPreviewer_Chart_ChartRefreshingError_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_GridPreviewer_Chart_ChartRefreshingError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Złe rzutowanie, konwersja lub formatowanie.
        /// </summary>
        internal static string MessageBoxShower_GridPreviewer_Panel_ImproperUserValueProblem_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_GridPreviewer_Panel_ImproperUserValueProblem_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana wartość jest niewłaściwa. Weź pod uwagę, że liczby powinny być zlokalizowane zgodnie z obecnymi ustawieniami regionalnymi systemu operacyjnego..
        /// </summary>
        internal static string MessageBoxShower_GridPreviewer_Panel_ImproperUserValueProblem_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_GridPreviewer_Panel_ImproperUserValueProblem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewłaściwa wartość indeksu.
        /// </summary>
        internal static string MessageBoxShower_GridPreviewer_Panel_IndexGreaterThanAllowedProblem_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_GridPreviewer_Panel_IndexGreaterThanAllowedProblem_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wskazany indeks byłby wyższy niż dozwolony. Zmiana odrzucona..
        /// </summary>
        internal static string MessageBoxShower_GridPreviewer_Panel_IndexGreaterThanAllowedProblem_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_GridPreviewer_Panel_IndexGreaterThanAllowedProblem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewłaściwa wartość indeksu.
        /// </summary>
        internal static string MessageBoxShower_GridPreviewer_Panel_IndexLowerThanAllowedProblem_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_GridPreviewer_Panel_IndexLowerThanAllowedProblem_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wskazany indeks byłby niższy niż dozwolony. Zmiana wycofana..
        /// </summary>
        internal static string MessageBoxShower_GridPreviewer_Panel_IndexLowerThanAllowedProblem_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_GridPreviewer_Panel_IndexLowerThanAllowedProblem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieważne punkty krzywej.
        /// </summary>
        internal static string MessageBoxShower_GridPreviewer_Panel_InvalidCurvePointsError_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_GridPreviewer_Panel_InvalidCurvePointsError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przynajmniej jedna z wartości punktów jest zbyt duża albo niewłaściwa, aby być wyświetloną na wykresie..
        /// </summary>
        internal static string MessageBoxShower_GridPreviewer_Panel_InvalidCurvePointsError_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_GridPreviewer_Panel_InvalidCurvePointsError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjątek podczas obliczeń.
        /// </summary>
        internal static string MessageBoxShower_GridPreviewer_Panel_PerformOperationError_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_GridPreviewer_Panel_PerformOperationError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można obliczyć wartości dla wszystkich wskazanych argumentów. Przeciążenie. Zmiany odrzucone..
        /// </summary>
        internal static string MessageBoxShower_GridPreviewer_Panel_PerformOperationError_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_GridPreviewer_Panel_PerformOperationError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unieważnione dane.
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_ChartRefreshingError_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_ChartRefreshingError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił problem podczas próby odświeżania wykresu lub ponownego obliczania wymiarów osi..
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_ChartRefreshingError_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_ChartRefreshingError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niespełnione wymaganie wstępne.
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_CurveTypeNotSelectedInfo_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_CurveTypeNotSelectedInfo_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz wybrać typ krzywej z sekcji &quot;Kontrola zestawem danych&quot;..
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_CurveTypeNotSelectedInfo_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_CurveTypeNotSelectedInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem metody uśredniania.
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_NotEnoughCurvesForMedianaStop_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_NotEnoughCurvesForMedianaStop_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz wskazać przynajmniej trzy krzywe, aby uśrednić je korzystając z mediany..
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_NotEnoughCurvesForMedianaStop_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_NotEnoughCurvesForMedianaStop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewspierana operacja.
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_OperationMalformRejectedStop_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_OperationMalformRejectedStop_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki tej operacji zostały odrzucone ze względu na niewłaściwe wartości..
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_OperationMalformRejectedStop_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_OperationMalformRejectedStop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niespełnione wymaganie wstępne.
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_PatternCurveNotChosenPrerequisite_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_PatternCurveNotChosenPrerequisite_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkielet krzywej wzorcowej nie został wybrany..
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_PatternCurveNotChosenPrerequisite_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_PatternCurveNotChosenPrerequisite_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostrzeżenie generowania punktów.
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_PointsNotValidToChartProblem_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_PointsNotValidToChartProblem_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Część z wygenerowanych punktów jest niewłaściwa, żeby wyświetlić je na wykresie. Punkty te zostaną usunięte z zestawu..
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_PointsNotValidToChartProblem_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_PointsNotValidToChartProblem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem wyboru danych.
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_SeriesSelectionProblem_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_SeriesSelectionProblem_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Żadna krzywa nie została jeszcze wygenerowana..
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_SeriesSelectionProblem_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_SeriesSelectionProblem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieważny indeks krzywej.
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_SpecifiedCurveDoesntExistProblem_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_SpecifiedCurveDoesntExistProblem_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane określonej krzywej nie istnieją..
        /// </summary>
        internal static string MessageBoxShower_MainWindow_Ui_SpecifiedCurveDoesntExistProblem_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_MainWindow_Ui_SpecifiedCurveDoesntExistProblem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzielenie przez zero.
        /// </summary>
        internal static string MessageBoxShower_PatternCurveDefiner_Hyperbolic_DivisionByZeroProblem_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_PatternCurveDefiner_Hyperbolic_DivisionByZeroProblem_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można podzielić przez 0.0000. Zamiast tego zostanie użyta wartość 0.0001..
        /// </summary>
        internal static string MessageBoxShower_PatternCurveDefiner_Hyperbolic_DivisionByZeroProblem_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_PatternCurveDefiner_Hyperbolic_DivisionByZeroProblem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd wymagań.
        /// </summary>
        internal static string MessageBoxShower_StatisticalAnalysis_Preview_NoSavedPresetsError_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_StatisticalAnalysis_Preview_NoSavedPresetsError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wygenerowano danych żadnej krzywej, więc nie zapisano żadnych ustawień wstępnych..
        /// </summary>
        internal static string MessageBoxShower_StatisticalAnalysis_Preview_NoSavedPresetsError_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_StatisticalAnalysis_Preview_NoSavedPresetsError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem wyboru danych.
        /// </summary>
        internal static string MessageBoxShower_StatisticalAnalysis_Preview_PointsNotValidToChartProblem_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_StatisticalAnalysis_Preview_PointsNotValidToChartProblem_Caption" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niektóre punkty nie mogą zostać pokazane na wykresie. Wykres nie zostanie odświeżony..
        /// </summary>
        internal static string MessageBoxShower_StatisticalAnalysis_Preview_PointsNotValidToChartProblem_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_StatisticalAnalysis_Preview_PointsNotValidToChartProblem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nierozpoznany błąd.
        /// </summary>
        internal static string MessageBoxShower_StatisticalAnalysis_Preview_UnrecognizedError_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_StatisticalAnalysis_Preview_UnrecognizedError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieznany błąd podczas odświeżania wykresu..
        /// </summary>
        internal static string MessageBoxShower_StatisticalAnalysis_Preview_UnrecognizedError_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_StatisticalAnalysis_Preview_UnrecognizedError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poza zakresem.
        /// </summary>
        internal static string MessageBoxShower_StatisticalAnalysis_Preview_ValueOutOfRangeProblem_Caption {
            get {
                return ResourceManager.GetString("MessageBoxShower_StatisticalAnalysis_Preview_ValueOutOfRangeProblem_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapewniona wartość nie znajduje się w określonym przedziale..
        /// </summary>
        internal static string MessageBoxShower_StatisticalAnalysis_Preview_ValueOutOfRangeProblem_Text {
            get {
                return ResourceManager.GetString("MessageBoxShower_StatisticalAnalysis_Preview_ValueOutOfRangeProblem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybór krzywej wzorcowej.
        /// </summary>
        internal static string PatternCurveDefiner_Form_Text {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwiąż.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Hyperbolic_Bound_ac {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Hyperbolic_Bound_ac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwiąż.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Hyperbolic_Bound_bd {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Hyperbolic_Bound_bd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiperbola.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Hyperbolic_Hyperbolic {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Hyperbolic_Hyperbolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Hyperbolic_Parameters {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Hyperbolic_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Polynomial_Parameters {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Polynomial_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wielomian.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Polynomial_Polynomial {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Polynomial_Polynomial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Parameters {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to piłokształtna.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Sawtooth {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Sawtooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sinusoidalna.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Sine {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Sine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prostokątna.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Square {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trójkątna.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Triangle {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Triangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krzywa falowa.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Waveform {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Waveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ fali.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_WaveType {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_WaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string PatternCurveDefiner_Ui_Cancel {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Ui_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PatternCurveDefiner_Ui_OK {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Ui_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analiza statystyczna.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Form_Text {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykres.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Chart {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks krzywej:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_CurveIndex {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_CurveIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ krzywej:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_CurveType {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_CurveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Dataset {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybór:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_DatasetSelection {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_DatasetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gęstość punktów (na przedział):.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Density1 {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Density1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formuła.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Formula {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ średniej:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_MeanType {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_MeanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szum:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Noise {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/D.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_NotApplicable {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość krzywych:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_NumberOfCurves1 {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_NumberOfCurves1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zjawisko:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Phenomenon {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Phenomenon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Preview {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deformacja.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_Deform {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_Deform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szum 0,1.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_Noise01 {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_Noise01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szum 0,5.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_Noise05 {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_Noise05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szum 1,0.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_Noise1 {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_Noise1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szum 2,0.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_Noise2 {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_Noise2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pik.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_Peek {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_Peek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odchylenie standardowe.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_StandardDeviation {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_StandardDeviation", resourceCulture);
            }
        }
    }
}
