//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pl_PL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pl_PL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PI.Locales.pl-PL", typeof(pl_PL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programie.
        /// </summary>
        internal static string About_Form_Text {
            get {
                return ResourceManager.GetString("About_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma:.
        /// </summary>
        internal static string About_Ui_AssemblyMetadata_Company {
            get {
                return ResourceManager.GetString("About_Ui_AssemblyMetadata_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadane aplikacji.
        /// </summary>
        internal static string About_Ui_AssemblyMetadata_Title {
            get {
                return ResourceManager.GetString("About_Ui_AssemblyMetadata_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja:.
        /// </summary>
        internal static string About_Ui_AssemblyMetadata_Version {
            get {
                return ResourceManager.GetString("About_Ui_AssemblyMetadata_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czasomierz:.
        /// </summary>
        internal static string About_Ui_Other_Counter {
            get {
                return ResourceManager.GetString("About_Ui_Other_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotor:.
        /// </summary>
        internal static string About_Ui_Other_Promoter1 {
            get {
                return ResourceManager.GetString("About_Ui_Other_Promoter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dr hab. Paweł Kowalczyk.
        /// </summary>
        internal static string About_Ui_Other_Promoter2 {
            get {
                return ResourceManager.GetString("About_Ui_Other_Promoter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repozytorium:.
        /// </summary>
        internal static string About_Ui_Other_Repository {
            get {
                return ResourceManager.GetString("About_Ui_Other_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inne.
        /// </summary>
        internal static string About_Ui_Other_Title {
            get {
                return ResourceManager.GetString("About_Ui_Other_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka logu:.
        /// </summary>
        internal static string About_Ui_TechnicalInformations_LogPath {
            get {
                return ResourceManager.GetString("About_Ui_TechnicalInformations_LogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework:.
        /// </summary>
        internal static string About_Ui_TechnicalInformations_NETFramework {
            get {
                return ResourceManager.GetString("About_Ui_TechnicalInformations_NETFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje techniczne.
        /// </summary>
        internal static string About_Ui_TechnicalInformations_Title {
            get {
                return ResourceManager.GetString("About_Ui_TechnicalInformations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia wykresu.
        /// </summary>
        internal static string ChartSettings_Form_Text {
            get {
                return ResourceManager.GetString("ChartSettings_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastosuj do krzywej:.
        /// </summary>
        internal static string ChartSettings_Ui_General_ApplyToCurve {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_General_ApplyToCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ChartSettings_Ui_General_OK {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_General_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykres.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_Chart_Title {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_Chart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osie.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_ChartArea_Axes {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_ChartArea_Axes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obszar wykresu.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_ChartArea_ChartArea {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_ChartArea_ChartArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obszar wykresu.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_ChartArea_Title {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_ChartArea_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie danych.
        /// </summary>
        internal static string ChartSettings_Ui_Tabs_Series_Title {
            get {
                return ResourceManager.GetString("ChartSettings_Ui_Tabs_Series_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WszystkieKomórki.
        /// </summary>
        internal static string Enums_AutoSizeColumnsMode_AllCells {
            get {
                return ResourceManager.GetString("Enums_AutoSizeColumnsMode_AllCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WszystkieKomórkiPozaNagłówkiem.
        /// </summary>
        internal static string Enums_AutoSizeColumnsMode_AllCellsExceptHeader {
            get {
                return ResourceManager.GetString("Enums_AutoSizeColumnsMode_AllCellsExceptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NagłówekKolumny.
        /// </summary>
        internal static string Enums_AutoSizeColumnsMode_ColumnHeader {
            get {
                return ResourceManager.GetString("Enums_AutoSizeColumnsMode_ColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WyświetloneKomórki.
        /// </summary>
        internal static string Enums_AutoSizeColumnsMode_DisplayedCells {
            get {
                return ResourceManager.GetString("Enums_AutoSizeColumnsMode_DisplayedCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WyświetloneKomórkiPozaNagłówkiem.
        /// </summary>
        internal static string Enums_AutoSizeColumnsMode_DisplayedCellsExceptHeader {
            get {
                return ResourceManager.GetString("Enums_AutoSizeColumnsMode_DisplayedCellsExceptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypełnienie.
        /// </summary>
        internal static string Enums_AutoSizeColumnsMode_Fill {
            get {
                return ResourceManager.GetString("Enums_AutoSizeColumnsMode_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Żadne.
        /// </summary>
        internal static string Enums_AutoSizeColumnsMode_None {
            get {
                return ResourceManager.GetString("Enums_AutoSizeColumnsMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fałsz.
        /// </summary>
        internal static string Enums_Boolean_False {
            get {
                return ResourceManager.GetString("Enums_Boolean_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prawda.
        /// </summary>
        internal static string Enums_Boolean_True {
            get {
                return ResourceManager.GetString("Enums_Boolean_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wszystkie.
        /// </summary>
        internal static string Enums_CurveApply_All {
            get {
                return ResourceManager.GetString("Enums_CurveApply_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uśredniona.
        /// </summary>
        internal static string Enums_CurveApply_Average {
            get {
                return ResourceManager.GetString("Enums_CurveApply_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idealna.
        /// </summary>
        internal static string Enums_CurveApply_Ideal {
            get {
                return ResourceManager.GetString("Enums_CurveApply_Ideal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zmodyfikowana.
        /// </summary>
        internal static string Enums_CurveApply_Modified {
            get {
                return ResourceManager.GetString("Enums_CurveApply_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uśredniona.
        /// </summary>
        internal static string Enums_DataSetCurveType_Average {
            get {
                return ResourceManager.GetString("Enums_DataSetCurveType_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idealna.
        /// </summary>
        internal static string Enums_DataSetCurveType_Ideal {
            get {
                return ResourceManager.GetString("Enums_DataSetCurveType_Ideal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zmodyfikowana.
        /// </summary>
        internal static string Enums_DataSetCurveType_Modified {
            get {
                return ResourceManager.GetString("Enums_DataSetCurveType_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wartość bezwzględna.
        /// </summary>
        internal static string Enums_GeometricMeanVariant_Absolute {
            get {
                return ResourceManager.GetString("Enums_GeometricMeanVariant_Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przesunięcie.
        /// </summary>
        internal static string Enums_GeometricMeanVariant_Offset {
            get {
                return ResourceManager.GetString("Enums_GeometricMeanVariant_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parzystość.
        /// </summary>
        internal static string Enums_GeometricMeanVariant_Parity {
            get {
                return ResourceManager.GetString("Enums_GeometricMeanVariant_Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to znak.
        /// </summary>
        internal static string Enums_GeometricMeanVariant_Sign {
            get {
                return ResourceManager.GetString("Enums_GeometricMeanVariant_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kwadratowy.
        /// </summary>
        internal static string Enums_KernelType_Boxcar {
            get {
                return ResourceManager.GetString("Enums_KernelType_Boxcar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epanechnikova.
        /// </summary>
        internal static string Enums_KernelType_Epanechnikov {
            get {
                return ResourceManager.GetString("Enums_KernelType_Epanechnikov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussa.
        /// </summary>
        internal static string Enums_KernelType_Gaussian {
            get {
                return ResourceManager.GetString("Enums_KernelType_Gaussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angielski.
        /// </summary>
        internal static string Enums_Languages_English {
            get {
                return ResourceManager.GetString("Enums_Languages_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polski.
        /// </summary>
        internal static string Enums_Languages_Polish {
            get {
                return ResourceManager.GetString("Enums_Languages_Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGM.
        /// </summary>
        internal static string Enums_MeanType_AGM {
            get {
                return ResourceManager.GetString("Enums_MeanType_AGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arytmetyczna.
        /// </summary>
        internal static string Enums_MeanType_Arithmetic {
            get {
                return ResourceManager.GetString("Enums_MeanType_Arithmetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centrum.
        /// </summary>
        internal static string Enums_MeanType_Central {
            get {
                return ResourceManager.GetString("Enums_MeanType_Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uogólniona.
        /// </summary>
        internal static string Enums_MeanType_Generalized {
            get {
                return ResourceManager.GetString("Enums_MeanType_Generalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geometryczna.
        /// </summary>
        internal static string Enums_MeanType_Geometric {
            get {
                return ResourceManager.GetString("Enums_MeanType_Geometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to harmoniczna.
        /// </summary>
        internal static string Enums_MeanType_Harmonic {
            get {
                return ResourceManager.GetString("Enums_MeanType_Harmonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herona.
        /// </summary>
        internal static string Enums_MeanType_Heronian {
            get {
                return ResourceManager.GetString("Enums_MeanType_Heronian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maksimum.
        /// </summary>
        internal static string Enums_MeanType_Maximum {
            get {
                return ResourceManager.GetString("Enums_MeanType_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mediana.
        /// </summary>
        internal static string Enums_MeanType_Median {
            get {
                return ResourceManager.GetString("Enums_MeanType_Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum.
        /// </summary>
        internal static string Enums_MeanType_Minimum {
            get {
                return ResourceManager.GetString("Enums_MeanType_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadaraya-Watsona.
        /// </summary>
        internal static string Enums_MeanType_NadarayaWatson {
            get {
                return ResourceManager.GetString("Enums_MeanType_NadarayaWatson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NN.
        /// </summary>
        internal static string Enums_MeanType_NN {
            get {
                return ResourceManager.GetString("Enums_MeanType_NN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMA.
        /// </summary>
        internal static string Enums_MeanType_SMA {
            get {
                return ResourceManager.GetString("Enums_MeanType_SMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tolerancyjna.
        /// </summary>
        internal static string Enums_MeanType_Tolerance {
            get {
                return ResourceManager.GetString("Enums_MeanType_Tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pogoń szumu.
        /// </summary>
        internal static string Enums_NadarayaWatsonVariant_NoiseCoursing {
            get {
                return ResourceManager.GetString("Enums_NadarayaWatsonVariant_NoiseCoursing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podstawienie.
        /// </summary>
        internal static string Enums_NadarayaWatsonVariant_Subsitution {
            get {
                return ResourceManager.GetString("Enums_NadarayaWatsonVariant_Subsitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dodawanie.
        /// </summary>
        internal static string Enums_Operations_Addition {
            get {
                return ResourceManager.GetString("Enums_Operations_Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stała.
        /// </summary>
        internal static string Enums_Operations_Constant {
            get {
                return ResourceManager.GetString("Enums_Operations_Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dzielenie.
        /// </summary>
        internal static string Enums_Operations_Division {
            get {
                return ResourceManager.GetString("Enums_Operations_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to potęgowanie.
        /// </summary>
        internal static string Enums_Operations_Exponentiation {
            get {
                return ResourceManager.GetString("Enums_Operations_Exponentiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logarytmowanie.
        /// </summary>
        internal static string Enums_Operations_Logarithmic {
            get {
                return ResourceManager.GetString("Enums_Operations_Logarithmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mnożenie.
        /// </summary>
        internal static string Enums_Operations_Multiplication {
            get {
                return ResourceManager.GetString("Enums_Operations_Multiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ujemny znak.
        /// </summary>
        internal static string Enums_Operations_Negative {
            get {
                return ResourceManager.GetString("Enums_Operations_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dodatni znak.
        /// </summary>
        internal static string Enums_Operations_Positive {
            get {
                return ResourceManager.GetString("Enums_Operations_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pierwiastkowanie.
        /// </summary>
        internal static string Enums_Operations_Rooting {
            get {
                return ResourceManager.GetString("Enums_Operations_Rooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odejmowanie.
        /// </summary>
        internal static string Enums_Operations_Substraction {
            get {
                return ResourceManager.GetString("Enums_Operations_Substraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pik.
        /// </summary>
        internal static string Enums_Phenomenon_Peek {
            get {
                return ResourceManager.GetString("Enums_Phenomenon_Peek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saturacja.
        /// </summary>
        internal static string Enums_Phenomenon_Saturation {
            get {
                return ResourceManager.GetString("Enums_Phenomenon_Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przesunięcie.
        /// </summary>
        internal static string Enums_StandardMeanVariant_Offset {
            get {
                return ResourceManager.GetString("Enums_StandardMeanVariant_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to definicja.
        /// </summary>
        internal static string Enums_StandardMeanVariant_Straight {
            get {
                return ResourceManager.GetString("Enums_StandardMeanVariant_Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siatka podglądu danych.
        /// </summary>
        internal static string GridPreviewer_Form_Text {
            get {
                return ResourceManager.GetString("GridPreviewer_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks.
        /// </summary>
        internal static string GridPreviewer_Ui_Dataset_Index {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Dataset_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zestaw danych.
        /// </summary>
        internal static string GridPreviewer_Ui_Dataset_Title {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Dataset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSizeColumnsMode:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_AutoSizeColumnsMode {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_AutoSizeColumnsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siatka zestawu danych.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_DatasetGrid {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_DatasetGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks końca:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_EndIndex {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_EndIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szybka edycja.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_FastEdit {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_FastEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiany zapisane.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_ChangesSaved {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siatka załadowana.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_GridPreviewerLoaded {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_GridPreviewerLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieważna wartość użytkownika.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_InvalidUserValue {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_InvalidUserValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacja odrzucona.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_OperationRejected {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_OperationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacja wycofana.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_OperationRevoked {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_OperationRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonano i odświeżono.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_PerformedAndRefreshed {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_PerformedAndRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartości odzyskane.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Info_ValuesRestored {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Info_ValuesRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_OK {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ operacji:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_OperationType {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonaj.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Perform {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Perform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odśwież.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Refresh {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przywróć.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Reset {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Save {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks początku:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_StartIndex {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajnik:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Addend {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Addend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawa:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Basis {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Basis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podzielnik:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Divisor {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Divisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykładnik:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Exponent {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Exponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnożnik:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Multiplier {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Multiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/D:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_NotApplicable {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjemnik:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Subtrahend {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Subtrahend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość:.
        /// </summary>
        internal static string GridPreviewer_Ui_Panel_Value1_Value {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Panel_Value1_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykres nieodświeżony.
        /// </summary>
        internal static string GridPreviewer_Ui_Preview_Info_ChartNotRepainted {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Preview_Info_ChartNotRepainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykres odświeżono.
        /// </summary>
        internal static string GridPreviewer_Ui_Preview_Info_ChartRefreshed {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Preview_Info_ChartRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd odświeżania wykresu.
        /// </summary>
        internal static string GridPreviewer_Ui_Preview_Info_ChartRefreshError {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Preview_Info_ChartRefreshError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd.
        /// </summary>
        internal static string GridPreviewer_Ui_Preview_Title {
            get {
                return ResourceManager.GetString("GridPreviewer_Ui_Preview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybór języka.
        /// </summary>
        internal static string LangSelector_Form_Text {
            get {
                return ResourceManager.GetString("LangSelector_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string LangSelector_Ui_Down_OkButton {
            get {
                return ResourceManager.GetString("LangSelector_Ui_Down_OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia....
        /// </summary>
        internal static string MainWindow_Menu_Chart_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Chart_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykres.
        /// </summary>
        internal static string MainWindow_Menu_Chart_Title {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Chart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importuj....
        /// </summary>
        internal static string MainWindow_Menu_File_Import {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik.
        /// </summary>
        internal static string MainWindow_Menu_File_Title {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje.
        /// </summary>
        internal static string MainWindow_Menu_Means_AveragingInfo {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means_AveragingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia....
        /// </summary>
        internal static string MainWindow_Menu_Means_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uśrednianie.
        /// </summary>
        internal static string MainWindow_Menu_Means_Title {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Means_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukryj.
        /// </summary>
        internal static string MainWindow_Menu_Panel_Hide {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utrzymuj wymiary.
        /// </summary>
        internal static string MainWindow_Menu_Panel_KeepProportions {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_KeepProportions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zablokuj.
        /// </summary>
        internal static string MainWindow_Menu_Panel_Lock {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        internal static string MainWindow_Menu_Panel_Title {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Panel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programie....
        /// </summary>
        internal static string MainWindow_Menu_Program_About {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończ.
        /// </summary>
        internal static string MainWindow_Menu_Program_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz język....
        /// </summary>
        internal static string MainWindow_Menu_Program_SelectLanguage {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analiza statystyczna....
        /// </summary>
        internal static string MainWindow_Menu_Program_StatisticalAnalysis {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_StatisticalAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string MainWindow_Menu_Program_Title {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Program_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastosuj.
        /// </summary>
        internal static string MainWindow_Panel_Average_Apply {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Average_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uśrednianie i wygładzanie.
        /// </summary>
        internal static string MainWindow_Panel_Average_Averaging {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Average_Averaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ średniej:.
        /// </summary>
        internal static string MainWindow_Panel_Average_MeanType {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Average_MeanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość krzywych:.
        /// </summary>
        internal static string MainWindow_Panel_Average_NumberOfCurves2 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Average_NumberOfCurves2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odch. standardowe:.
        /// </summary>
        internal static string MainWindow_Panel_Average_StandardDeviation1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Average_StandardDeviation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uśredniona.
        /// </summary>
        internal static string MainWindow_Panel_Average_Title {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Average_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkielet krzywej:.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_CurveScaffold1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_CurveScaffold1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hiperboliczny.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_CurveScaffold2_Hyperbolic {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_CurveScaffold2_Hyperbolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie wybrany.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_CurveScaffold2_NotChosen {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_CurveScaffold2_NotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wielomianowy.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_CurveScaffold2_Polynomial {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_CurveScaffold2_Polynomial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to falowy.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_CurveScaffold2_Waveform {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_CurveScaffold2_Waveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cały zestaw krzywych.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_CurvesSet {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_CurvesSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkty przedziału:.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_Density {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Końcowy punkt x:.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_EndingXPoint {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_EndingXPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygeneruj zestaw.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_GenerateSet {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_GenerateSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkielet krzywej wzorcowej.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_IdealCurveScaffold {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_IdealCurveScaffold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość krzywych:.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_NumberOfCurves1 {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_NumberOfCurves1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Początkowy punkt x:.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_StartingXPoint {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_StartingXPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idealna.
        /// </summary>
        internal static string MainWindow_Panel_Ideal_Title {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Ideal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks krzywej:.
        /// </summary>
        internal static string MainWindow_Panel_Modified_CurveIndex {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_CurveIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość krzywych:.
        /// </summary>
        internal static string MainWindow_Panel_Modified_CurvesNumber {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_CurvesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ krzywej:.
        /// </summary>
        internal static string MainWindow_Panel_Modified_CurveType {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_CurveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrola zestawem danych.
        /// </summary>
        internal static string MainWindow_Panel_Modified_DatasetControl {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_DatasetControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szum Gaussa.
        /// </summary>
        internal static string MainWindow_Panel_Modified_GaussianNoise {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_GaussianNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zniekształć.
        /// </summary>
        internal static string MainWindow_Panel_Modified_Malform {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_Malform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż zestaw danych.
        /// </summary>
        internal static string MainWindow_Panel_Modified_ShowDataSet {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_ShowDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otoczenie:.
        /// </summary>
        internal static string MainWindow_Panel_Modified_Surrounding {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_Surrounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmodyfikowana.
        /// </summary>
        internal static string MainWindow_Panel_Modified_Title {
            get {
                return ResourceManager.GetString("MainWindow_Panel_Modified_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praca inżynierska.
        /// </summary>
        internal static string MainWindow_Ui_Form_Text {
            get {
                return ResourceManager.GetString("MainWindow_Ui_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia średnich.
        /// </summary>
        internal static string MeansSettings_Form_Text {
            get {
                return ResourceManager.GetString("MeansSettings_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia arytmetyczno-geometryczna (AGM).
        /// </summary>
        internal static string MeansSettings_Ui_AGM {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_AGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość:.
        /// </summary>
        internal static string MeansSettings_Ui_Amount {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metoda centrum.
        /// </summary>
        internal static string MeansSettings_Ui_Central {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja kończąca:.
        /// </summary>
        internal static string MeansSettings_Ui_FinisherFunction {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_FinisherFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uogólniona średnia (potęgowa).
        /// </summary>
        internal static string MeansSettings_Ui_Generalized {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Generalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia geometryczna.
        /// </summary>
        internal static string MeansSettings_Ui_Geometric {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Geometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia harmoniczna.
        /// </summary>
        internal static string MeansSettings_Ui_Harmonic {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Harmonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia Herona.
        /// </summary>
        internal static string MeansSettings_Ui_Heronian {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Heronian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozmiar jądra:.
        /// </summary>
        internal static string MeansSettings_Ui_KernelSize {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_KernelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ jądra:.
        /// </summary>
        internal static string MeansSettings_Ui_KernelType {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_KernelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procent masy:.
        /// </summary>
        internal static string MeansSettings_Ui_MassPercent {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_MassPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ważona jądrem średnia Nadarayi-Watsona.
        /// </summary>
        internal static string MeansSettings_Ui_NadarayaWatson {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_NadarayaWatson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygładzanie najbliższymi sąsiadami (NN).
        /// </summary>
        internal static string MeansSettings_Ui_NN {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_NN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MeansSettings_Ui_OK {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rząd:.
        /// </summary>
        internal static string MeansSettings_Ui_Rank {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metoda tolerancyjna.
        /// </summary>
        internal static string MeansSettings_Ui_ToleranceHeader {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_ToleranceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerancja:.
        /// </summary>
        internal static string MeansSettings_Ui_ToleranceText {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_ToleranceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wariant:.
        /// </summary>
        internal static string MeansSettings_Ui_Variant {
            get {
                return ResourceManager.GetString("MeansSettings_Ui_Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd alokacji pamięci.
        /// </summary>
        internal static string Messages_General_OutOfMemoryException_Caption {
            get {
                return ResourceManager.GetString("Messages_General_OutOfMemoryException_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjątek typu OutOfMemoryException został rzucony. Dzieje się tak, kiedy nie wystarczającej ilości pamięci, aby kontynuować wykonywanie programu..
        /// </summary>
        internal static string Messages_General_OutOfMemoryException_Text {
            get {
                return ResourceManager.GetString("Messages_General_OutOfMemoryException_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieważna operacja.
        /// </summary>
        internal static string Messages_GridPreviewer_ChartRefreshing_Caption {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_ChartRefreshing_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd odświeżania wykresu, najprawdopodobniej związany z ponownym obliczaniem skal osi (zbyt wielkie do wyświetlenia)..
        /// </summary>
        internal static string Messages_GridPreviewer_ChartRefreshing_Text {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_ChartRefreshing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Złe rzutowanie, konwersja lub formatowanie.
        /// </summary>
        internal static string Messages_GridPreviewer_ImproperUserValue_Caption {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_ImproperUserValue_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana wartość jest niewłaściwa. Weź pod uwagę, że liczby powinny być zlokalizowane zgodnie z obecnymi ustawieniami regionalnymi systemu operacyjnego..
        /// </summary>
        internal static string Messages_GridPreviewer_ImproperUserValue_Text {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_ImproperUserValue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewłaściwa wartość indeksu.
        /// </summary>
        internal static string Messages_GridPreviewer_IndexGreaterThanAllowed_Caption {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_IndexGreaterThanAllowed_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wskazany indeks byłby wyższy niż dozwolony. Zmiana odrzucona..
        /// </summary>
        internal static string Messages_GridPreviewer_IndexGreaterThanAllowed_Text {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_IndexGreaterThanAllowed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewłaściwa wartość indeksu.
        /// </summary>
        internal static string Messages_GridPreviewer_IndexLowerThanAllowed_Caption {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_IndexLowerThanAllowed_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wskazany indeks byłby niższy niż dozwolony. Zmiana wycofana..
        /// </summary>
        internal static string Messages_GridPreviewer_IndexLowerThanAllowed_Text {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_IndexLowerThanAllowed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieważne punkty krzywej.
        /// </summary>
        internal static string Messages_GridPreviewer_InvalidCurvePoints_Caption {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_InvalidCurvePoints_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przynajmniej jedna z wartości punktów jest zbyt duża albo niewłaściwa, aby być wyświetloną na wykresie..
        /// </summary>
        internal static string Messages_GridPreviewer_InvalidCurvePoints_Text {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_InvalidCurvePoints_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjątek podczas obliczeń.
        /// </summary>
        internal static string Messages_GridPreviewer_PerformOperation_Caption {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_PerformOperation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można obliczyć wartości dla wszystkich wskazanych argumentów. Przeciążenie. Zmiany odrzucone..
        /// </summary>
        internal static string Messages_GridPreviewer_PerformOperation_Text {
            get {
                return ResourceManager.GetString("Messages_GridPreviewer_PerformOperation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unieważnione dane.
        /// </summary>
        internal static string Messages_MainWindow_ChartRefreshing_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_ChartRefreshing_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił problem podczas próby odświeżania wykresu lub ponownego obliczania wymiarów osi..
        /// </summary>
        internal static string Messages_MainWindow_ChartRefreshing_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_ChartRefreshing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zestaw danych zaimportowany.
        /// </summary>
        internal static string Messages_MainWindow_CurveDataSetImported_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_CurveDataSetImported_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik z zestawem krzywych zaimportowano z powodzeniem..
        /// </summary>
        internal static string Messages_MainWindow_CurveDataSetImported_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_CurveDataSetImported_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niespełnione wymaganie wstępne.
        /// </summary>
        internal static string Messages_MainWindow_CurveTypeNotSelected_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_CurveTypeNotSelected_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz wybrać typ krzywej z sekcji &quot;Kontrola zestawem danych&quot;..
        /// </summary>
        internal static string Messages_MainWindow_CurveTypeNotSelected_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_CurveTypeNotSelected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewspierana operacja.
        /// </summary>
        internal static string Messages_MainWindow_OperationMalformRejected_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_OperationMalformRejected_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki tej operacji zostały odrzucone ze względu na niewłaściwe wartości..
        /// </summary>
        internal static string Messages_MainWindow_OperationMalformRejected_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_OperationMalformRejected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niespełnione wymaganie wstępne.
        /// </summary>
        internal static string Messages_MainWindow_PatternCurveNotChosen_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_PatternCurveNotChosen_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkielet krzywej wzorcowej nie został wybrany..
        /// </summary>
        internal static string Messages_MainWindow_PatternCurveNotChosen_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_PatternCurveNotChosen_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostrzeżenie generowania punktów.
        /// </summary>
        internal static string Messages_MainWindow_PointsNotValidToChart_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_PointsNotValidToChart_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Część z wygenerowanych punktów jest niewłaściwa, żeby wyświetlić je na wykresie. Punkty te zostaną usunięte z zestawu..
        /// </summary>
        internal static string Messages_MainWindow_PointsNotValidToChart_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_PointsNotValidToChart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem wyboru danych.
        /// </summary>
        internal static string Messages_MainWindow_SeriesSelection_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_SeriesSelection_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Żadna krzywa nie została jeszcze wygenerowana..
        /// </summary>
        internal static string Messages_MainWindow_SeriesSelection_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_SeriesSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieważny indeks krzywej.
        /// </summary>
        internal static string Messages_MainWindow_SpecifiedCurveDoesNotExist_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_SpecifiedCurveDoesNotExist_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane określonej krzywej nie istnieją..
        /// </summary>
        internal static string Messages_MainWindow_SpecifiedCurveDoesNotExist_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_SpecifiedCurveDoesNotExist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieobsługiwany błąd importowania.
        /// </summary>
        internal static string Messages_MainWindow_UnsupportedImportingError_Caption {
            get {
                return ResourceManager.GetString("Messages_MainWindow_UnsupportedImportingError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd podczas importowania zestawu danych krzywych. Zobacz log, aby uzyskać więcej informacji..
        /// </summary>
        internal static string Messages_MainWindow_UnsupportedImportingError_Text {
            get {
                return ResourceManager.GetString("Messages_MainWindow_UnsupportedImportingError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewspierany typ średniej.
        /// </summary>
        internal static string Messages_MeansSettings_NotSupportedFinisherFunction_Caption {
            get {
                return ResourceManager.GetString("Messages_MeansSettings_NotSupportedFinisherFunction_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrany typ średniej nie jest dozwolony dla tej metody uśredniania..
        /// </summary>
        internal static string Messages_MeansSettings_NotSupportedFinisherFunction_Text {
            get {
                return ResourceManager.GetString("Messages_MeansSettings_NotSupportedFinisherFunction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem wyboru danych.
        /// </summary>
        internal static string Messages_StatisticalAnalysis_PointsNotValidToChart_Caption {
            get {
                return ResourceManager.GetString("Messages_StatisticalAnalysis_PointsNotValidToChart_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niektóre punkty nie mogą zostać pokazane na wykresie. Wykres nie zostanie odświeżony..
        /// </summary>
        internal static string Messages_StatisticalAnalysis_PointsNotValidToChart_Text {
            get {
                return ResourceManager.GetString("Messages_StatisticalAnalysis_PointsNotValidToChart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nierozpoznany błąd.
        /// </summary>
        internal static string Messages_StatisticalAnalysis_Unrecognized_Caption {
            get {
                return ResourceManager.GetString("Messages_StatisticalAnalysis_Unrecognized_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieznany błąd podczas odświeżania wykresu..
        /// </summary>
        internal static string Messages_StatisticalAnalysis_Unrecognized_Text {
            get {
                return ResourceManager.GetString("Messages_StatisticalAnalysis_Unrecognized_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poza zakresem.
        /// </summary>
        internal static string Messages_StatisticalAnalysis_ValueOutOfRange_Caption {
            get {
                return ResourceManager.GetString("Messages_StatisticalAnalysis_ValueOutOfRange_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapewniona wartość nie znajduje się w określonym przedziale..
        /// </summary>
        internal static string Messages_StatisticalAnalysis_ValueOutOfRange_Text {
            get {
                return ResourceManager.GetString("Messages_StatisticalAnalysis_ValueOutOfRange_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybór krzywej wzorcowej.
        /// </summary>
        internal static string PatternCurveDefiner_Form_Text {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwiąż.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Hyperbolic_Bound_ac {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Hyperbolic_Bound_ac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwiąż.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Hyperbolic_Bound_bd {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Hyperbolic_Bound_bd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiperbola.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Hyperbolic_Hyperbolic {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Hyperbolic_Hyperbolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Hyperbolic_Parameters {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Hyperbolic_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Polynomial_Parameters {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Polynomial_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wielomian.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Polynomial_Polynomial {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Polynomial_Polynomial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Parameters {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to piłokształtna.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Sawtooth {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Sawtooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sinusoidalna.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Sine {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Sine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prostokątna.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Square {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trójkątna.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Triangle {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Triangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krzywa falowa.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_Waveform {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_Waveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ fali.
        /// </summary>
        internal static string PatternCurveDefiner_Tabs_Waveform_WaveType {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Tabs_Waveform_WaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string PatternCurveDefiner_Ui_Cancel {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Ui_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PatternCurveDefiner_Ui_OK {
            get {
                return ResourceManager.GetString("PatternCurveDefiner_Ui_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analiza statystyczna.
        /// </summary>
        internal static string StatisticalAnalysis_Form_Text {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykres.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Chart {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks krzywej:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_CurveIndex {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_CurveIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ krzywej:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_CurveType {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_CurveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Dataset {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybór:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_DatasetSelection {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_DatasetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ średniej:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_MeanType {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_MeanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szum:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Noise {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zjawisko:.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Phenomenon {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Phenomenon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_Preview_Title {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_Preview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szum.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_Noise {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pik.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_Peek {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_Peek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturacja.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_Saturation {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odchylenie standardowe.
        /// </summary>
        internal static string StatisticalAnalysis_Ui_StandardDeviation_Title {
            get {
                return ResourceManager.GetString("StatisticalAnalysis_Ui_StandardDeviation_Title", resourceCulture);
            }
        }
    }
}
